@echo off
echo Running pdflatex (1/4)...
pdflatex -interaction=nonstopmode main
echo Running bibtex (2/4)...
bibtex main
echo Running pdflatex (3/4)...
pdflatex -interaction=nonstopmode main
echo Running pdflatex (4/4)...
pdflatex -interaction=nonstopmode main
echo Done! Check main.pdf
pause
